name: redis

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/redis.yaml'
      - '.nais/redis/redis.yaml'
      - '.nais/redis/redisexporter.yaml'

jobs:
  apply-redis-cache:
    name: Apply Redis instance for caching
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ".nais/redis/redis.yaml,.nais/redis/redisexporter.yaml"
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ".nais/redis/redis.yaml,.nais/redis/redisexporter.yaml"
